version: '3.8'

networks:
  app-frontend:
    driver: ${NETWORKS_DRIVER}

volumes:
  nginx-certs:
  nginx-html:
  nginx-vhost:
  acme-state:

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    build:
      context: ./docker/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    hostname: ${COMPOSE_PROJECT_NAME}-nginx-proxy
    restart: ${RESTART_POLICY}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - nginx-vhost:/etc/nginx/vhost.d
    networks:
      - app-frontend

  acme-companion:
    image: nginxproxy/acme-companion
    hostname: ${COMPOSE_PROJECT_NAME}-acme-companion
    restart: ${RESTART_POLICY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - nginx-vhost:/etc/nginx/vhost.d
      - acme-state:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=${COMPOSE_PROJECT_NAME}-nginx-proxy
    networks:
      - app-frontend
    depends_on:
      - nginx-proxy

  app:
    restart: always
    build: .
    hostname: ${COMPOSE_PROJECT_NAME}-fe-app
    environment:
      - VIRTUAL_HOST=${FRONTEND_HOST}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${FRONTEND_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - app-frontend